### ISSUE TITLE
(Unicode?) Path Encoding not working on Windows

### ISSUE THREAD

**Issue by qwerdbeta** [cvpr2020-inpainting-anonymous/Pytorch-MADF#2]
When I try to run test.py I get errors in site.py complaining of the paths showing encoded characters. I try to encode them in cp1252 or utf8 and it then traces errors that I have a null character in path ("ValueError: stat: embedded null character in path"). On windows 10.

When I just try to run the code as it is in the repo, I get this error:

Fatal Python error: initsite: Failed to import the site module
Traceback (most recent call last):
  File "G:\pythonAI\Pytorch-MADF\lib\site.py", line 770, in <module>
    main()
  File "G:\pythonAI\Pytorch-MADF\lib\site.py", line 747, in main
    paths_in_sys = addsitepackages(paths_in_sys)
  File "G:\pythonAI\Pytorch-MADF\lib\site.py", line 279, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "G:\pythonAI\Pytorch-MADF\lib\site.py", line 202, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "G:\pythonAI\Pytorch-MADF\lib\site.py", line 166, in addpackage
    for line in f:
  File "G:\pythonAI\Pytorch-MADF\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 850: character maps to < undefined >

**Comment by likeyo1** [comment]
Excuse me, have you solved it？
